### ISSUE TITLE
Warning: Unsupported request method: rascal/filesystem/unwatch

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#209] opened 2022-12-07 10:24 UTC
**Describe the bug**

```
2022-12-07 11:23:23,443 [pool-3-thread-1] WARN - org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint Unsupported request method: rascal/filesystem/unwatch
2022-12-07 11:23:37,399 [pool-3-thread-1] WARN - org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint Unsupported request method: rascal/filesystem/unwatch
```

**Comment by DavyLandman** [comment] 2022-12-07 10:59
I think this is a duplicate of #159 ?

**Comment by DavyLandman** [comment] 2023-09-22 11:37
Closing this as duplicated for #159.

**Closed by DavyLandman** 2023-09-22 11:37 UTC
Labels: bug
