### ISSUE TITLE
Crawling project locations in a terminal is slow

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-language-servers#138] opened 2022-01-24 08:21 UTC
This is observable with, e.g., `crawl(l)` and `find(l, "rsc")` on sufficiently large locations. As a workaround, use the corresponding `file:///` location.

The problem seems to be that the implementation communicates over JSON-RPC for each file.

**Comment by DavyLandman** [comment] 2022-01-24 08:46
I've also noticed this. It's not just the crawling btw, it's also file access. Since that to goes over the JSON-RPC bridge in a base64 encoding.

However, this will be hard to solve generically. We could make a distinction in the protocol for resolveable and virtual file systems. So that should be part of the #128 I think.

**Comment by jurgenvinju** [comment] 2022-01-24 11:15
The issue at hand is caused by an older implementation of the "project" scheme as a ILogicalResourceResolver that connects to the JSON-RPC socket every time a file is accessed. Newer implementations of the same scheme are already working that use a pre-registered list of project workspace locations. Those are as fast as the `file` scheme. 

We have to wire the IDEServices interface implementations a bit differently to get access to the same information. That will take a little bit of tinkering. Perhaps a days work?

Indeed this indicates that possible implementations for #128 will suffer from similar performance losses. It could worth our while to distinguish between "prefix" resolvers that simply provide an abstraction over a location in the `file` system, and truly opaque filesystem providers which require the full API to be mapped. Such providers may be slow for other reasons and the additional JSON-RPC hop could _not_ the bottleneck.

**Comment by DavyLandman** [comment] 2022-09-01 09:39
The VFS (#158 ) made this a lot quicker. CLosing for now.

**Closed by DavyLandman** 2022-09-01 09:39 UTC
