### ISSUE TITLE
Renaming a module whose name occurs in a qualified function call fails

### ISSUE THREAD

**Issue by sungshik** [usethesource/rascal-language-servers#524] opened 2024-11-18 11:04 UTC
Renaming a module whose name occurs in a qualified function call fails (but not the other way around).

Example:

```rascal
module Foo
//     ^^^ F2 here fails

void f() {}

void g() {
    Foo::f();
//  ^^^ F2 here succeeds
}
```

This exception is thrown in case of a failure:

```
java.lang.NullPointerException
	at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:762)
	at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:752)
	at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:558)
	at org.rascalmpl.vscode.lsp.rascal.RascalLanguageServices.lambda$getRename$13(RascalLanguageServices.java:216)
	at org.rascalmpl.vscode.lsp.util.EvaluatorUtil.lambda$runEvaluator$0(EvaluatorUtil.java:96)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by toinehartman** [comment] 2024-11-26 16:28
Thanks for reporting! Interesting to see this seems to fail within Rascal. I cannot reproduce that on the Rascal side of things. I added a test there, just to be sure: 046df83a.

Anyway, this issue uses some strange, soon-to-be-deprecated behavior anyway; one should not rename a module from a qualified reference to a declaration in that module (but instead, from the module header or an import). This will change in #531.
All in all, I'll close this.

**Closed by toinehartman** 2024-11-26 16:28 UTC
Labels: bug
